@startuml
left to right direction

package "nl" {
    package "connectplay" {
        package "scoreplay" {

            ' ---- Core packages ----
            package "utilities"
            package "stores"
            package "exceptions"

            ' ---- UI ----
            package "ui" {
                package "components"
                package "theme"
                package "notifications"
            }

            ' ---- ViewModels ----
            package "viewModels" {
                package "session "
                package "profile "
                package "main"
                package "login"
            }

            ' ---- Screens ----
            package "screens" {
                package "notifications "
                package "session"
                package "profile"
                package "home"
            }

            ' ---- Room ----
            package "room" {
                package "events"
                package "entities"
                package "dao"
            }

            ' ---- Models ----
            package "models" {
                package "user"
                package "session  "
                package "search"
                package "leaderboard"
                package "game"
                package "friends"
                package "dto"
                package "events "

                ' ---- Auth subpackages of Models ----
                package "auth" {
                    package "register"
                    package "login "
                }
            }

            ' ---- API ----
            package "api" {
                package "http"
            }

        }
    }
}
@enduml
